server:
  port: 8080
# Hibernate 相关配置
spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect # 方言
        hbm2ddl:
          auto: update                            # 建表方式
  datasource:
    url: jdbc:mysql://localhost:3306/shenzhou?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8             # 数据库连接
    username: root            #用户名
    password: root               #密码
    driver-class-name: com.mysql.cj.jdbc.Driver  # 数据库驱动
#hibernate其他配置
hibernate:
  show_sql: true         # 显示Sql
entitymanager:
  packagesToScan: com.hgc.bean       # 自动扫描的包前缀